# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Pontus CI/CD

on:
#  push:
#    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
#    container: pontusvisiongdpr/pontus-track-graphdb-odb-pt:latest

    steps:

#    - name: echo PWD
#      run: pwd

#    - name: echo GITHUB_WORKSPACE
#      run: echo "${GITHUB_WORKSPACE}"

#    - name: echo github.workspace
#      run: echo "${github.workspace}"

    - name: Make file runnable && Build docker-lib
#     echo "${github.workspace}" |
#     echo "${GITHUB_WORKSPACE}"
      run: |
        chmod +x "${GITHUB_WORKSPACE}/.github/script.sh" |
        "${GITHUB_WORKSPACE}/.github/script.sh"
      
#    - name: Build Docker Conf
#      run: build-docker-conf.sh
      
#    - name: Docker Build & Push Action
#      uses: mr-smithers-excellent/docker-build-push@v5.6
#      with:
#        image: pontusvisiongdpr/pontus-track-graphdb-odb-pt:latest
#        tags: latest
#        registry: docker.io
#        dockerfile: Dockerfile.ci
#        username: ${{ secrets.DOCKER_USERNAME }}
#        password: ${{ secrets.DOCKER_PASSWORD }}

      
#  publish:
#    needs: build

# --------------- original:

#    - uses: actions/checkout@v2

#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v2
#      with:
#        java-version: '8'
#        distribution: 'adopt'
#        cache: maven
