# STEP 3: AFTER push it to DockerHub (gonna need Docker Credentials as GitHub secret)

name: Push Image to DockerHub

on:
  push:
    branches: [ master ]

jobs:
  push-dockerhub:

        runs-on: ubuntu-latest
        
        steps:
          - uses: actions/checkout@v2

          - name: Docker Push Action
            id: docker-push
            uses: mr-smithers-excellent/docker-build-push@v5.6
            with:
              image: 'pontusvisiongdpr/pontus-track-graphdb-odb-pt'
              tags: latest
              registry: 'docker.io'
#              dockerfile: Dockerfile.ci
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}
#      publish:
#        needs: build

          - name: Get Outputs
            run: |
              echo "Full name of the Docker image with registry prefix: ${{ steps.docker-push.outputs.imageFullName }}"
              echo "Name of the Docker image with owner prefix: ${{ steps.docker-push.outputs.imageName }}"
              echo "Tags for the Docker image: ${{ steps.docker-push.outputs.tags }}"
